### ISSUE TITLE
S21 : Start game

### ISSUE THREAD

**Issue by ayoposiolubamisaye** [JonathanRamos2002/CS482-War#31]
As a Player I want to start the game so that I can play the game
Points = 3
Priority = High
Definition of done: When I am able to successfully start the game

**Comment by JonathanRamos2002** [comment]
S21: Start Game -> clicking on the deck starts the game, and UI updates accordingly for both players
[de58a87](https://github.com/JonathanRamos2002/CS482-War/commit/de58a872d56a3a008d31d6c95377e8e5d0acb60e)
