### ISSUE TITLE
S22 : Bot

### ISSUE THREAD

**Issue by ayoposiolubamisaye** [JonathanRamos2002/CS482-War#32]
As a Player I want to Play with bot  so that I can play without friends
Points = 5
Priority = Med
Definition of done: When bot plays the game with player

**Comment by JonathanRamos2002** [comment]
improved user interface to play game
[1920568](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/19205689aa6b2dbd3ec9dacc40098b009f3d5fcd)

**Comment by JonathanRamos2002** [comment]
shuffle animation
[301dcdc](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/301dcdc708d666f712fe0f63ff8ddee7833ade45)

**Comment by JonathanRamos2002** [comment]
deal cards animation complete
[2ac4b36](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/2ac4b368d2350ec52bf788866078cfb956c4c2df)

**Comment by JonathanRamos2002** [comment]
war scenario logic working perfectly, fourth card gets dragged to determine what the fourth card is
[dc57021](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/dc570211f97d4e005fbfee38323c34d7c2f5598e)

**Comment by JonathanRamos2002** [comment]
war animation
[c7484b4](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/c7484b4cb7100d88975902d0df9bbd87b069dfb5)

**Comment by JonathanRamos2002** [comment]
back-to-back war handled
[e36d628](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/e36d628b012cdf9fe5f1d3baae7a9064b1d9fe68)

**Comment by JonathanRamos2002** [comment]
completed bot user story
[ba113b1](https://github.com/JonathanRamos2002/CS482-War/pull/38/commits/ba113b11e653d893d197ac64076e922e29ab88c0)
